apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-example
  labels:
    app: metrics-example
  annotations:
    kubernetes.io/change-cause: ver1
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: metrics-example
  replicas: 5
  template:
    metadata:
      labels:
        app: metrics-example
    spec:
      containers:
        - name: metrics-example
          image: ondrejsika/metrics-example
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-example
  labels:
    app: metrics-example
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: metrics-example
