apiVersion: v1
kind: Pod
metadata:
  name: private-pod
  labels:
    svc: example
spec:
  containers:
    - name: hello
      image: registry.sikahq.com/pseudo-private/hello-world:latest
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
        limits:
          memory: 20Mi
          cpu: 20m
  imagePullSecrets:
    - name: private-registry-credentials
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: private-registry-credentials
stringData:
  .dockerconfigjson: '{"auths": {"registry.sikahq.com": {"auth": "cHNldWRvLXByaXZhdGUtdXNlcjphc2RmYXNkZg=="}}}'
