apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-nfs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # persistentVolumeReclaimPolicy: Recycle
  # persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  mountOptions:
    - hard
  nfs:
    path: /nfs
    server: nfs.sikademo.com
