#
# @see https://hub.docker.com/r/jboss/wildfly
#
FROM jboss/wildfly:21.0.2.Final

#
# @see https://github.com/goldmann/wildfly-docker-deployment-example << simplest docker/widlfly example
#
COPY target/simplest.jaxrs.war /opt/jboss/wildfly/standalone/deployments/