version: "3.8"
services:
  traefik:
      image: traefik:1.7
      command: |
          --accesslog \
          --api \
          --metrics \
          --metrics.prometheus \
          --metrics.prometheus.entryPoint="traefik" \
          --web \
          --docker \
          --docker.watch \
          --docker.network=traefik \
          --docker.exposedbydefault=false \
          --entryPoints="Name:http Address::80" \
          --defaultentrypoints="http"
  counter:
    build: .
    image: toce/counter
    ports:
      - ${PORT:-80}:80
    deploy:
      # lze resit - docker-compose up --scale <service>=<n>
      # upadne na port is already allocated, reseni je proxy
      replicas: 2
    # zajisti poradi spusteni dle zavislosti
    depends_on:
      - redis
  redis: # na tohle se pak lze odkazovat v docker network, viz. app.py (ř6)
    image: redis
    command:
      - "--appendonly"
      - "yes"
    volumes:
  # cestu za dvojteckou -zjistim, ze kouknu 
  # via docker inspect redis a 
  # hledam volumes a tim zjistim
  # ... docker image redis history | grep VOLUME
      - redis-data:/data
  # test:
  #   image: ondrejsika/curl
  #   command:
  #     - -f
  #     - counter
  #   depends_on:
  #     - counter      
volumes:
  # tento nazev volume je pak mozny
  # pouzit v compose/services/volumes
  redis-data:
