apiVersion: v1
kind: ConfigMap
metadata:
  name: envfrom
data:
  MY_HELLO: hello
  MY_WORLD: world
---
apiVersion: v1
kind: Pod
metadata:
  name: envfrom
spec:
  containers:
    - name: debian
      image: debian
      command:
        - /bin/sh
        - -c
        - env | grep MY_
      envFrom:
        - configMapRef:
            name: envfrom
  restartPolicy: Never
